config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  root 'pages#home'

  get  '/home',    to: 'pages#home'
  get  '/about',    to: 'pages#about'
end

app/models/excercise.rb
class Excercise < ActiveRecord::Base
  belongs_to :user
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :date, presence: true
  validates :workout, presence: true
  validates :mood, presence: true
  validates :length, presence: true
  has_many :excercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/excercises_controller.rb
class ExcercisesController < ApplicationController

  before_action :find_excercise, only:[:show, :edit, :update, :destroy]

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  private

  def find_excercise
  end

  def set_exc_params
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController

  before_action :find_workout, only: [:show, :edit, :update, :destroy]

  def index
    @workouts = Workout.all
  end

  def new
    @workout=Workout.new
  end

  def show
  end

  def create
    @workout=Workout.create(workout_params)
    if @workout.save
      redirect_to @workout
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout
    else
      render 'edit'
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path
  end

  private

    def find_workout
      @workout=Workout.find(params[:id])
    end

    def workout_params
      params.require(:workout).permit(:date, :mood, :workout, :length)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/excercises_helper.rb
module ExcercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/excercises/_excercises.html.haml
%h1 excercises

app/views/excercises/_form.html.haml
%h1 form_for excercise

app/views/excercises/edit.html.haml
%h1 editing excercises

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Workout Log
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  .container
    = yield

app/views/pages/about.html.haml
%h1 this is the about page

app/views/pages/home.html.haml
%h1 this is the home page
%br
=link_to "New Workout",new_workout_path,class: "btn btn-sm btn-default"
=link_to "All Workouts",workouts_path,class: "btn btn-sm btn-default"

app/views/workouts/_form.html.haml
.container
  = simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
    -if @workout.errors.any?
      #error_explanation
        %h2= pluralize(@job.errors.count, "error")
        prohibited this todo_list from being saved
        %ul
          -@workout.errors.full_messages.each do |message|
            %li= message
    =f.input :workout, label:'Workout', input_html: {class: "form-control"}
    =f.input :mood, label:'Mood', input_html: {class: "form-control"}
    =f.input :date, label:'Date', input_html: {class: "form-control"}
    =f.input :length, label:'Workout length', input_html: {class: "form-control"}
    %br/
    .form
      =f.button :submit,class: "btn btn-sm btn-default"
      =link_to "Back",root_path,class: "btn btn-sm btn-default"

app/views/workouts/edit.html.haml
%h1 Edit Workout
=render 'form'
=link_to "Back",root_path,class: "btn btn-sm btn-default"

app/views/workouts/index.html.haml
%br
=link_to "Home",root_path,class: "btn btn-sm btn-default"
-@workouts.each do |workout|
  %ul
    %h2
      %li= link_to workout.date.strftime('%A, %b %d ,%Y'),workout
    %p
      %li= workout.workout

app/views/workouts/new.html.haml
%h1 New Workout
=render 'form'

app/views/workouts/show.html.haml
%h1= @workout.date.strftime('%A, %b %d ,%Y')
%p= @workout.workout
%p= @workout.mood
%p= @workout.length

=link_to "Back",workouts_path,class: "btn btn-sm btn-default"
=link_to "Edit",edit_workout_path,class: "btn btn-sm btn-default"
=link_to "Delete",workout_path,method: :delete ,class: "btn btn-sm btn-default"